### ISSUE TITLE
[init] 프로젝트 기초세팅

### ISSUE THREAD

**Issue by l2zh** [donggukthonN/donggukthon_2023_12_F#1]
## ❗ 이슈 요약

프로젝트 기초세팅

## 📝 todo

- [x] layer 분리 (data, domain, presentation)
- [x] hilt 세팅
- [x] util 함수 추가
- [x] Application 클래스 추가
- [x] sdk 버전 설정
- [x] dependencies 추가
