### ISSUE TITLE
[init] 리소스 추가

### ISSUE THREAD

**Issue by Dan2dani** [donggukthonN/donggukthon_2023_12_F#3]
## ❗ 이슈 요약
리소스 추가

## 📝 todo
- [x] 컬러 리소스 추가
- [x] 폰트 리소스 추가
- [x] 버튼 style 지정
